### ISSUE TITLE
Starter checklist for the project

### ISSUE THREAD

**Issue by p0larstern** [p0larstern/submit-routine#1]
will add and discuss about features here for some time until a working program will be ready , not in a specific order
- [ ] storing username password locally
- [ ] checking existence of file
- [ ] assigning flag names in a text file
- [ ] think of various flags
- [ ] create readme
- [ ] create a text file for future features
